#!/bin/bash

function install_luarocks {
    echo "Installing lua..."
    sudo pacman -S lua
    echo "Installing luarocks..."
    sudo pacman -S luarocks
}

sudo steamos-readonly disable
install_luarocks
sudo steamos-readonly enable
